import { type Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { headers } from 'next/headers';
import { TestFakesProvider } from './testing/TestFakesProvider';
import {
  getTestFakesFrom
} from './testing/TestFakesAdapterService';
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Aero logic",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <TestFakesProvider
        fakes={getTestFakesFrom(headersList)}>
        <div className="container mx-auto h-screen" style={{maxWidth: '640px'}}>
          <div className="pt-8 md:pt-16 h-full">
            <div
              className="py-4 px-10 h-full bg-white rounded-t-md">
              <header className="pb-8">
                <Link href="/">
                  <img className="-ml-2"
                       alt="Aero Logic"
                       src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIQAAAAwCAYAAADQH9LEAAAAAXNSR0IArs4c6QAADI9JREFUeF7tWguMXFUZ/v8zr27ZbXnVLbtzz50tKyRFRVBBQxBDAiKoKPKoPBTQqCAaCBgUFSpESdAQBQWjQVFUxFixvAy+XwiCEtTYUGi3e8+dXWiLPLpl2+7ee37vN567zI6zdGZ3u2XTe5KbOzP3zDn/+f7v/K9zmbKWIVCHAGdoZAjUI5ARIuPDJAQyQmSEyAiRcWBqBDILkbEjsxAZBzILkXGgRQQyl9EiUHtKt4wQe4qmW1xnRogWgdpTumWE2FM03eI6M0K0CNSe0i0jxEuaznuedywzLyaiEjMvsNY+Fobh3/YUMmCdMyJET0/Pwnw+f5OIPBOG4WXzGbhKpfJma+2DDWt41Bjzht2xrr6+Pj+O4zOstX+oVqt/nSsZZkQIrfWXiOgzTth9jTHPzZXgsz1PpVKBRfggMy8SkeVEdC4R/coYc/xsz9XCeHmt9VoiWoa+cRzvPzQ09J8W/jfjLtMmhOd5BzLzujoJjjbG/HnGEr0CBvA873hmvl9E7gzD8JTdIJLSWgdEVJ7rzTYTQtzCzOcT0feICDvroiAIvrEbwJv1KX3fP0lE7hGRH4VheNasT9DCgL7vHyYip4vIfWEY/qmFv1B3d/deGzdufLGVvlP1mRYhtNYwZeuJaDUzXyciD4AYxhiY2Umtr6/v4DiOP8vMR4rIQhHBzruqWq0O1XVEQAdibQvD8MN9fX3dURSdqJR6rbW2O5/PX71hwwaY0LQpz/MuZmbs3qOIaICIVkVRtHJ4eHh0JoDgv57nnczMPyeiW40x500xXrsyKN/33wN5ReTVRGSJ6HFr7XXVavXZdA7P897EzBUiWiAiORF5tFqt/nOqNVUqlb1F5ItJv3c7i/JbEVnZKokax50WITzPuxEWgZmP3b59+8OlUmkrlGKMObB+gnSnud/WAGsi6iKiTVEUvXF4eDh0Cqh3PxcT0VcbBF1pjPmC+409z1vFzO8lohER+TszI/DrEpGHwjAEQQD2tJvv++8TkZ8S0beMMR9tMlBbMnie15PIeDcRHf5/CmD+UBAE38Hvy5YtWxxF0fMNfTYZY7qbLca57d/XuZa020gURcuGh4efaReEtgmxdOnSJcVicZMjQD8Ridb630SEQGwisOzv7180Njb2JBG9SkRWhGF4B34bHx9/JDHFBxHRN40xF0Bg3/cPh2JT4Zn5Ccd67JaL6hWjtX4nEQHckTiOlw8NDVV7enq8fD7/FwfMacYYKHPazfO8Fcx8OzPfHATBhY0DtSkD4oH7iOjtRARLenkURWuVUocopaDMnxhjzkjncGTcT0TyzAwXPGKMWdRsMVrre4joJCK611r7AfRRSj3igtH6TdQyFm0TQmv96SRPvxb+VURuY+a9mflTjv3HGWN+7ZR8loj8oC4wg1s40S0SwdJ1xpjLXd9jReQ3Tup7oyg6Haa/DvgrjDHX4rnWGqb8ZBG5Be6lDsjLROTLs+H3Pc97PzNjfV8Pw/ATTQjRsgxaa1gsBNsDHR0dr1+7du0IxiuXy/sqpZA53G2Mgbmf1LTW+xARXEnVGAPL2vg8HXeSNdBagxi1uM4Y8/2WmeA6tkWIxBKcBkZPNQkzXxkEwTVOcWlKujoRbgMRnQlrgWci8otSqbRi3bp1W/C9zmdv6ujo6E9BA+F93z80CIJ/EVHkyLMWFkZEzgvD8NZUFq31uxJS3uXcxlvaBaK+v9b6bCK6bSpC+L7fsgye513oNsFVxpir03lSSwsswjA8sVFe3/cPEJFhIlpjjDmkCSFA1BuaxTlIoQcHB7dPB4N2CQE/fiXYzsyrrbVVZob7AJsh3ETerrW+I1nM6fVCYfFJnn99akXqdnfNmuwkiKt111qLI9URYRjCPNZaHamaAtgOOCkh6t1aA2FalsH3fRTuLmDmU4MgWJWOU6lUllprnyKi+40xJzTK59yggfsMguDgJoS4mYg+NtvZXbuEuIuIsBPPMcZAgbXW399fGhsbqzGys7OztGbNmjGtNQgCFoM0N+RyuTsGBgZMM8V4nncuM38Xu9IYU/OFU7U0XhGRM8MwvL2OEF9h5ktno3aQugwi+rYx5iNNlFGLmVqRwfO8VK7zwzDEGmutXC6/Tin1j6kI0dvbW87lcgi6m7oMz/PuY+Z3NFrKdojfrG/LhHCRci1VVErtMzg4OCka1lrDTyKleitSHt/3Pw6T27jg3t7e/XK5HNxOnFYBPc87g5l/PJU/bdidtZ3RkAEgcINbQWA7EW9MF5w619g07dRatyyD53mXwCo2kJ211vDz5yAgNMYgUJ7U6lxG0ywjiTG+lsQYn2wMSsvlcr9SCsHrz9KgvR0cWiaE1hrCI0hZZYw5tcmuuSr5bSVSRmPMJXVBE7oi+MRuPlBEPu9iiQnTXqlU3mat/V0r/t/VNR7HoMgCROTB5H8nJKYVMQrIesDg4ODT7YCAobTWSP1qvhoHXC4TgjtEJrBDRF4oFAqfGxgYeKEdGer7JnWFa+ACkvrDCpcdYLrVxhjUJwg4xHF8FDPnEKwnc17i1gFsEXvhzOgmZ2GOVEo95J7DWt/vsiz8B7HaTq3tjCyE7/uniMiq1AI0DuaY+SR2QxAEl+J5XZbQ2P3ROI5PRsqIB+4gZ3Aqf9lk99RkafgdNYmzwzCEW2u34ewAET1qJFM2a+2haZEoxaMVGXzfv75OuelfQLZJitNa/zJJTY97ORmMMYU0wE4zvib9HygUCqesX78ec7TVWrYQGBWFE+yQqWZYsmRJ5+bNm1EpnCgMlcvlXmY+mpn7mHmLiKzt7Oz8I+KM+nEQFCqlNgdBgHrCThuCsjiOj1FKLUHVNKlsPjyTA6ByudxRKBQWWWuVtZZxLxaLOfddichz9RVFCNiODL7vI7U+AtiIyGNKKVQhUZ+40RgD048NtCyxpAdba2Nmjq21kVIqVkpFcRzHRDQUhiEyj4nmed5rlFLHiAhS+Y3M/HAQBLAc0yrOtUWInWop69AyAmkckhwQnh0EwQ9b/uMu7pgRYhcD3Gz4tBKKZ4VCoXs6pn1XiZ0RYlch68b1fR81litQPRSRLYlJRxEKqTvaxcYYZAuvmJYR4n81gQ5mRnFtX0T3SaaEcvxia+0iZsahWRczdybl9oXu6iAiXCUiKjJzMTl7KSA7wAklkh33NhrwRaDa26BxxAMb3PskqN9ss9ZuS44AcHSNg8KRpKaCIPkFXESEF49wPdvV1fVMY/w1m2xqmxBaaxSb9gN4AI6I8A4iFp0CBqAWOLAQEecdQAAJDcEO5t2BWgQzR0kqCoBwoTydfkadoyAi25VS20UE/QFe/TXpt+QoHsfrm6EgKMrJAXnw+15ORsiKC3JjDTg4ghKRZaTAPw9FKKWgkJpyrLUvOoWNMvM2KBEyJbt/DFculxuPoggBINZkmVlwieDGOK08LI7jfXK53FNxHA8opcbiOK69uwlyKaVSGSEnSAgyQrYaQZ2skBfYY/7NODVOqqAblVJIs1H1HI7jeIiZq4VCIXy5BGAqEk2HEKhA4lCmBh7MoFJqi7V2KzMjwwBQ2621Ozo6OsZHR0ejYrFoFy5cWIt6R0dH1djYWGdXV9eObdu25aMoyhWLxfSei6Iob63N5XK5g5gZhTAAtiCKIhwhLwW4ScFrf2be35XMARaAg5IBJkgI0oAs4ynJoBnMD+2AAMycx652ZMAdBMIzZD+48F8oe5yZa781+YximI++zDzunuMeOaKn9xrJkTk48oMwyCJwBy41AuFurcW9Ribc3QXRa/K71iEinbBe7pU/rB8EX+xqKCmJkNE8wcyDsEioD+3MmrRNiJ0N2O7z5cuXF0dGRjykTUopnOr1uhQK6SpMbY+7sCOQcj0lIk9jV+CeVC1x35jP5zfGcYyq3kze61SVSqVYKpUKW7duLebz+WIulyuMjY0VlVK1z1EU4TPcQzGOY7gLvIOJ7yAYjqwn7o54qRsBCfEZlhJprEJLv4OM7jMrpaCXmm5gYRymU+kqJfoEeepIBQuEcnklCII7W9HNLieEezMbNYiKtdZPBMSO8kUEnzURwZyiZh+KSAhz584/hmD+rLXDw8PDsBTTyqtbASHr8xICs0IIHOWWSqX+5P0IvDGFC6/YpRd8HgKoQRGB6cI9UEqZOI6DhlfpMt3sZgRmhRCu7LsOUbO1Fu9a4hpI3uIZSMvTu3md2fQtIjArhGhxrqzbPEAgI8Q8UNJcipgRYi7RngdzZYSYB0qaSxEzQswl2vNgrowQ80BJcyliRoi5RHsezJURYh4oaS5FzAgxl2jPg7n+CwQEsIuG6tUIAAAAAElFTkSuQmCC"
                  />
                </Link>
              </header>
              {children}
            </div>
          </div>
        </div>
      </TestFakesProvider>
      </body>
    </html>
  );
}
